services:
  eureka-server:
    build:
      context: ./EurekaServer
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-latest}
    image: eureka-server:${VERSION:-latest}
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-latest}
    image: api-gateway:${VERSION:-latest}
    container_name: api-gateway
    environment:
        - SERVER_URL=http://host.docker.internal:8761
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  order-service:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-latest}
    image: order-service:${VERSION:-latest}
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_URL=http://host.docker.internal:8761

    depends_on:
      - eureka-server

  payment-service:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
      args:
        - VERSION=${VERSION:-latest}
    image: payment-service:${VERSION:-latest}
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_URL=http://host.docker.internal:8761

    depends_on:
      - eureka-server

networks:
  default:
    name: microservices-network