services:
  eureka-server:
    image: chamika3131/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: chamika3131/api-gateway:latest
    container_name: api-gateway
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
    ports:
      - "9000:8080"
    depends_on:
      - eureka-server

  order-service:
    image: chamika3131/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - PAYMENT_SERVICE_URL=http://payment-service:8081/api/payments
    depends_on:
      - eureka-server

  payment-service:
    image: chamika3131/payment-service:latest
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

networks:
  default:
    name: microservices-network