spring:
  application:
    name: PaymentService
  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true

server:
  port: 8081

eureka:
  client:
    service-url:
        defaultZone: ${EUREKA_SERVER_URL}
