spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:h2:mem:orderdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}


# environment variables

payment:
  service:
    url: ${PAYMENT_SERVICE_URL}