name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build and test Spring Boot applications
      - name: Build Order Service
        run: mvn -B clean install -f OrderService/pom.xml

      - name: Build Payment Service
        run: mvn -B clean install -f PaymentService/pom.xml

      - name: Build Eureka Server
        run: mvn -B clean install -f EurekaServer/pom.xml

      - name: Build API Gateway
        run: mvn -B clean install -f ApiGateway/pom.xml

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images
      - name: Build and push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./OrderService
          push: true
          tags: chamika3131/order-service:latest
          cache-from: type=registry,ref=chamika3131/order-service:latest
          cache-to: type=inline

      - name: Build and push Payment Service
        uses: docker/build-push-action@v4
        with:
          context: ./PaymentService
          push: true
          tags: chamika3131/payment-service:latest
          cache-from: type=registry,ref=chamika3131/payment-service:latest
          cache-to: type=inline

      - name: Build and push Eureka Server
        uses: docker/build-push-action@v4
        with:
          context: ./EurekaServer
          push: true
          tags: chamika3131/eureka-server:latest
          cache-from: type=registry,ref=chamika3131/eureka-server:latest
          cache-to: type=inline

      - name: Build and push API Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./ApiGateway
          push: true
          tags: chamika3131/api-gateway:latest
          cache-from: type=registry,ref=chamika3131/api-gateway:latest
          cache-to: type=inline

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "compose.yml"  # Changed from docker-compose.yml to compose.yml
          target: "/home/${{ secrets.SSH_USER }}/demo-microservices"

      - name: Deploy to AWS Lightsail
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/demo-microservices
            docker compose pull  # Changed from docker-compose to docker compose
            docker compose down --remove-orphans
            docker compose up -d
            docker system prune -f